name: starter_kit
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^5.0.4
  dartz: ^0.10.1
  diox: ^5.0.0
  flutter_hooks: ^0.18.5+1
  freezed_annotation: ^2.2.0
  hooks_riverpod: ^2.1.3
  json_annotation: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
